apiVersion: v1
kind: Secret
metadata:
  name: {{ include "ci-training-lab.fullname" . }}
  labels:
    {{- include "ci-training-lab.labels" . | nindent 4 }}
type: Opaque
data:
  # Giá trị được base64-encode tự động bởi Helm
  api-key: {{ .Values.secret.apiKey | b64enc | quote }}
